### ISSUE TITLE
Css in Javascript

### ISSUE THREAD

**Issue by GitProdEnv** [EmilTholin/sqip-loader#2]
Is it possible to use it for background images as well? Actually I'm using emotion, a css-in-javascript library.

`import bgImage from '.....'; `

`const { preview, src } = bgImage;`
`// Using javascript library to attach background-image to Component`
`const className = css``background: url(${preview})``;` (note: around css `` should be single one)

Inserting ${src} into background: url() at least the image is shown, but then there is no progressive image loading :(

**Comment by EmilTholin** [comment]
Hi @GitProdEnv!

I have never tried using `sqip-loader` with emotion before, but the generated preview works in CSS. Try surrounding `preview` with `"` and see if you get a different result, or try `background-image`.

```javascript
const className = css`background: url("${preview}");`
const className = css`background-image: url("${preview}");`
```
