### ISSUE TITLE
[Feature request]: caching

### ISSUE THREAD

**Issue by vxna** [EmilTholin/sqip-loader#3]
Next webpack with [persistent caching](https://github.com/webpack/changelog-v5/blob/master/README.md#persistent-caching) is coming this year, afaik it's caching mode works with `sqip-loader` just fine but webpack 5 itself is still in alpha and not ready. 

I've tried to port `babel-loader` [cache](https://github.com/babel/babel-loader/blob/master/src/cache.js) but without any success. 

From my current tests with [cache-loader](https://github.com/webpack-contrib/cache-loader) userland code just fails to resolve `image.src` at second build  since image object now exist only in `.cache-loader/*.json` and `image.src` represents url from the previous build and `file-loader` does not emit anything anymore.

Would you like to take a look at supporting `cache-loader` or other caching options?

**Comment by EmilTholin** [comment]
Hey @vxna! Thank you for your feedback!

Yeah, having a filesystem cache for this loader would be awesome, as it's so slow when cold started. As you noticed it's very tricky to get a filesystem cache right, so I'd rather wait for webpack 5 instead of trying to add our own to this loader.
